app = "nicobruno-backend"   # <-- must be globally unique; change if Fly complains
primary_region = "gru"      # "gru" = SÃ£o Paulo; you can use "ams" if you prefer NL

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DATABASE_URL = "sqlite:////data/nicobruno.db"


[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "nicobruno_data"
  destination = "/data"
